### ISSUE TITLE
Nested properties in Kibana

### ISSUE THREAD

**Issue by Couto** [daniel-cottone/serverless-es-logs#80]
I know this issue is not directly related to serverless-es-logs however you might be able to provide some guidance, I hope this can help other devs starting with the ELK stack (like myself).

We are sending logs using this plugin. Logs are collected with Winston, so they are mostly JSON objects with several properties.

Because we are using this plugin, all properties, in Kibana, are named something like e.g.: `$event.statusCode` , at least if we use the default filter, which is fine.

Now while I'm able to create tables and some visualizations using those names, I can't create filters nor searches:

![screen shot 2018-10-17 at 12 23 20](https://user-images.githubusercontent.com/165314/47083106-974fe600-d207-11e8-94aa-892b19d624e2.png)

How do you usually handle this sort of scenario? I know this is a problem with Kibana itself, but I assume that you might have already lost some time investigating this so I hope you could share your findings!

Thank you! :)

**Comment by daniel-cottone** [comment]
Hey @Couto,

I wish I had a good answer for you. Unfortunately I haven't been able to find a solution or workaround for this. The bit of digging I did seems to indicate that the root cause is that the search parameter for `$event.statusCode` is missing from the request.

The request that would typically be sent to elasticsearch would be in this format:
```json
{
  "query": {
    "bool": {
      "must": [{
        "match": {
          "some_field": {
            "query": "something",
            "type": "phrase"
          }
        }
      }, {
        "$event.statusCode": {
          "field_two": {
            "query": "something",
            "type": "phrase"
          }
        }
      }]
    }
  }
}
```

I am seeing this request being made to elasticsearch:
```json
{
  "query": {
    "bool": {
      "must": [{
        "match": {
          "field_one": {
            "query": "something",
            "type": "phrase"
          }
        }
      }, {
        "match": {}
      }]
    }
  }
}
```

This seems to indicate to me that there is a problem with Kibana processing `$` in the property name. Hopefully this gives you something more to work with; if you are able to find a solution please share it here!

**Comment by daniel-cottone** [comment]
Thanks for digging in @Couto. I went ahead and cut a new release `2.0.1` that should fix this issue, we are now prefixing `event` with `@` instead of `$`.

If you would like to add some features that you feel are missing, please raise an issue to discuss them! I'd like to support whatever you think is missing so that you don't have to run your own fork.
